
<!--<form action="<?php /*echo $block->getFormAction() */?>" method="post">
    <input name="firstname" type="text">
    <input name="lastname" type="text">
    <input name="phone" type="text">
    <input name="bookingTime" type="date">
    
</form>-->

<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form"
              action="<?php echo $this->getFormAction(); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Fill Detail')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field firstname required">
                            <label class="label" for="firstname"><span><?= $block->
                                    escapeHtmlAttr(__('First Name')) ?></span></label>
                            <div class="control">
                                <input name="name" id="name" title="FirstName" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>
                        <div class="field lastname required">
                            <label class="label" for="title"><span><?= $block->
                                    escapeHtmlAttr(__('Last Name')) ?></span></label>
                            <div class="control">
                                <input name="lname" id="lname" title="LastName" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>
                        <div class="field email required">
                            <label class="label" for="title"><span><?= $block->
                                    escapeHtmlAttr(__('Email')) ?></span></label>
                            <div class="control">
                                <input name="email" id="email" title="Email" value="" class="input-text" type="text">
                            </div>
                        </div>
                        <div class="field company required">
                            <label class="label" for="title"><span><?= $block->
                                    escapeHtmlAttr(__('Company')) ?></span></label>
                            <div class="control">
                                <input name="company" id="company" title="Company" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>



                        <div class="field telephone">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Telephone')) ?></span></label>
                            <div class="control">
                                <input name="telephone" id="telephone" title="Telephone" value="" class="input-text"
                                       type="text">
                            </div>
                        </div>
                        <div class="field comment required">
                            <label class="label" for="comment">
                                <span><?= $block->escapeHtml(__('What’s on your mind?')) ?></span>
                            </label>
                            <div class="control">
                <textarea name="comment"
                          id="comment"
                          title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>"
                          class="input-text"
                          cols="5"
                          rows="3"
                          data-validate="{required:true}"></textarea>
                            </div>
                        </div>
                        <div class="field gender">
                            <label class="label" for="gender"><span><?= $block->
                                    escapeHtmlAttr(__('Gender')) ?></span></label>
                            <div class="control">
                             <b>Male</b> <input name="gender" id="male" title="male"  class="input-text" type="radio" value="male">
                                <b>Female</b>
                                <input name="gender" id="female" title="female" class="input-text" type="radio" value="female">
                                <b>Others</b>
                                <input name="gender" id="others" title="others" class="input-text" type="radio" value="other">
                            </div>
                        </div>

                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Submit"><span><?= $block->
                            escapeHtmlAttr(__('Submit')) ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>